import type { Metadata } from "next";
import { MantineProvider, createTheme } from "@mantine/core";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";

export const metadata: Metadata = {
  title: "Events App",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: "Open Sans, sans-serif",
  colors: {
    white: [
      "#FFF",
      "#FFF",
      "#FFF",
      "#FFF",
      "#FFF",
      "#FFF",
      "#FFF",
      "#FFF",
      "gray",
      "gray",
    ],
  },
  primaryColor: "white",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"bg-black bg-grid-white/[0.04]"}>
        <MantineProvider defaultColorScheme="dark" theme={theme}>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
